development:
  adapter: em_mysql2
  encoding: utf8
  reconnect: true
  database: cloudstorge
  pool: 5
  username: root
  password: '111111'
  #host: '10.0.0.10'
  host: '172.17.10.236'
  
production:
  adapter: em_mysql2
  encoding: utf8
  reconnect: true
  database: cloudstorge
  pool: 10
  username: root
  password: '111111'
  host: '172.17.10.236'
  #host: '10.0.0.10'
