development:
  adapter: em_mysql2
  encoding: utf8
  reconnect: true
  database: cloudstorge
  pool: 5
  username: root
  password: '111111'
  host: '10.0.0.10'
  
production:
  adapter: em_mysql2
  encoding: utf8
  reconnect: true
  database: cloudstorge
  pool: 200
  username: root
  password: '111111'
  host: '10.0.0.10'
